title: Jiabin Luo's Homepage
description: Welcome to my website!
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://jiabinluo.github.io" # change this to the base hostname & protocol for your site


google_analytics:

# 作者信息
author:
  name: Jiabin Luo
  avatar: ./jiabinluo.png # 你的照片路径
  bio: "Ph.D. student at Peking University, focusing on multi-modal machine learning, autonomous driving, and robot learning."
  email: your-email@example.com
  github: jiabinluo



# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: ""
remote_theme: pages-themes/hacker@v0.2.0

# social
author: Jiabin Luo
image: /thumbnail-jumbo.png
twitter:
  username: Jiabin Luo

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
